### ISSUE TITLE
Error when binning in parallel

### ISSUE THREAD

**Issue by niklasvm** [guillermo-navas-palencia/optbinning#103]
Hi there

Thank you for a really great package. I am facing an error when trying to fit multiple variables in parallel by setting `n_jobs` to -1 or any other number for that matter:
```
MaybeEncodingError: Error sending result:  ********************
************************************
Reason: 'TypeError("cannot pickle '_thread.lock' object")'
```

I am trying to put together a reproducible example which I will share below.

I used this successfully around 3 months ago so I think it is related to new dependencies.

**Comment by niklasvm** [comment]
Update:

I have forked master and run unit tests using
```
pytest ./tests/
```

A number of tests are failing, one of which shows the error above. I am using `Python 3.9.4`
![image](https://user-images.githubusercontent.com/18314300/118495979-007f9900-b724-11eb-902b-62e850f0ec13.png)

**Comment by guillermo-navas-palencia** [comment]
Hi @niklasvm,

A few comments on the latter error messages:
1. TDigest is an optional dependency. In order to run the unit tests install the dependencies in requirements.txt and test_requirements.txt
```
python -m pip install --upgrade pip
pip install -r test_requirements.txt
pip install -r requirements.txt
```
2. All binning process tests pass on Linux and Windows. See GitHub Actions: https://github.com/guillermo-navas-palencia/optbinning/actions/runs/789857432/workflow

Could you provide more details regarding your OS and dependencies versions?

**Comment by niklasvm** [comment]
I will do so. I am running this inside the latest `jupyter/pyspark-notebook:latest` docker image.

**Comment by niklasvm** [comment]
I have created a Dockerfile that reproduces the error:
```
FROM python:3.9.4

RUN apt-get update && \
    apt-get install -y git

RUN git clone https://github.com/guillermo-navas-palencia/optbinning.git && \
    cd optbinning && \
    python -m pip install --upgrade pip && \
    pip install -r test_requirements.txt && \
    pip install -r requirements.txt
    
RUN echo pwd

RUN export PYTHONPATH='.' && \
    cd optbinning && \
    pytest ./tests/
```

**Comment by niklasvm** [comment]
I have forked the repo and triggered github actions to run and am getting the same failures: https://github.com/niklasvm/optbinning/pull/1

**Comment by guillermo-navas-palencia** [comment]
Yes, I was able to reproduce the error with GitHub Actions. This particular code did not change since the last release when all tests passed. I am guessing this might be due to some recent changes in multiprocessing because I cannot reproduce the error in my local environment. I will look into this, perhaps I might replace multiprocessing with joblib. In the meantime, I suggest using just one thread.

Thanks, I will keep you posted.

**Comment by niklasvm** [comment]
Thank you

**Comment by guillermo-navas-palencia** [comment]
The bugfix is in master:
https://github.com/guillermo-navas-palencia/optbinning/pull/105/checks?check_run_id=2613203412

**Comment by niklasvm** [comment]
Thank you so much. Everything is working again on my side as well.
