### ISSUE TITLE
User-defined split points replication error

### ISSUE THREAD

**Issue by DomagojGalic** [guillermo-navas-palencia/optbinning#174]
Hi,

I was trying to replicate an example from the tutorial for adding user-defined split points [link](http://gnpalencia.org/optbinning/tutorials/tutorial_binary.html#User-defined-split-points), however my results differ significantly.

<img width="602" alt="replication_issue" src="https://user-images.githubusercontent.com/16214790/172798779-c30bb3dd-bd0d-4791-9bcd-b69a6540b6e3.PNG">

Namely, as you can see, I get only one bin spanning $\langle -\infty, +\infty \rangle$. This is also something I experienced on my own project, which motivated me to try to replicate the example and work from there.

I tried experimenting a bit and when I play around with `user_splits_fixed` this sometimes happens. Also sometimes even though I set a split as fixed it is completely disregarded (not to as extreme way as here, meaning that some splits are present in final binning but not the ones set as fixed).

Any help would be greatly appreciated.

**Comment by guillermo-navas-palencia** [comment]
Hi @DomagojGalic,

I think you are not using the same variable used in the example (mean radius instead of mean texture). I attach a screenshot showing the correct results.

![image](https://user-images.githubusercontent.com/40094942/172816976-e9c49518-03ee-4d36-86a5-0340a2614473.png)

In addition, note that ``information()`` shows status INFEASIBLE. This status confirms that the splits provided for a particular variable are not valid (it is not possible to obtain a feasible/optimal solution).

**Comment by DomagojGalic** [comment]
Hi @guillermo-navas-palencia,

Firstly, thank you for taking the time to address my issue.
You are completely correct,  I referred to the wrong variable, my mistake.
However, I'm experiencing similar problems when tweaking the user defined splits a bit. Let me give you two examples:
1. When I simply add a user split at 12 and set it as fixed (also using the "cp" as a solver), the following happens:
![image](https://user-images.githubusercontent.com/16214790/173187312-6cd0ed69-1d19-401f-bcab-f3725d4b9fc9.png)

2. If I do not add any additional split points, but simply fix different points, the same thing happens
![image](https://user-images.githubusercontent.com/16214790/173187479-2ee6bd4b-e782-4266-8472-d5c0f41bbafc.png)

I'm also attaching you the entire notebook and environment file for easier replication.
[replication.zip](https://github.com/guillermo-navas-palencia/optbinning/files/8883869/replication.zip)

Again, thank you for taking the time and helping me, I really appreciate it!

**Comment by guillermo-navas-palencia** [comment]
1. It is INFEASIBLE because forcing monotonic trend "descending" (note that monotonic_trend="auto" is used by default) and user splits the problem is infeasible. You can either set monotonic_trend=None or try other monotonic trend:

![image](https://user-images.githubusercontent.com/40094942/174887567-422ccf52-0ab6-4718-8039-6795e284b150.png)


![image](https://user-images.githubusercontent.com/40094942/174887290-505a86e7-6a02-468d-8035-58bf7b87db0f.png)
Since these settings are a bit more advanced, I would recommend you to set verbose=True.

2. 
![image](https://user-images.githubusercontent.com/40094942/174887856-54d4b06d-1416-4e1f-8f00-5d91ebc379c2.png)
![image](https://user-images.githubusercontent.com/40094942/174887951-973da71f-ed9e-4ac1-ade6-d72c057f3809.png)

**Comment by DomagojGalic** [comment]
Hi @guillermo-navas-palencia,

Thank you very much for your help, it's very much appreciated.
