### ISSUE TITLE
Saving Scorecard object to PMML

### ISSUE THREAD

**Issue by denmase** [guillermo-navas-palencia/optbinning#200]
Hello @guillermo-navas-palencia,

First of all, thank you for this amazing package. As a Python newbie, I'd like to ask whether there is any way to save/export Scorecard object into PMML. I know I can export sklearn-based model into PMML using sklearn2pmml, but currently I can't find a way to save scorecard object into PMML. I've tried to convert the pickle using:

 `java -jar pmml-sklearn-example-executable-1.7.13.jar --pkl-input scorecard.pkl --pmml-output scorecard.pmml`

However, it is complaining that `The object (Python class optbinning.scorecard.scorecard.Scorecard) is not a PMMLPipeline`. Is there any way to do so?

Thanks in advance for any help.

Regards,
Agung

**Comment by guillermo-navas-palencia** [comment]
Hello @denmase.

AFAIK, sklearn2pmml is a wrapper to [jpmml-sklearn](https://github.com/jpmml/jpmml-sklearn#features) which only supports the ``BinningProcess`` class: https://github.com/jpmml/jpmml-sklearn/blob/master/pmml-sklearn-extension/src/test/resources/extensions/optbinning.py.

I think you could contact jpmml-sklearn's maintainers and ask for support for the ``Scorecard`` class.

**Comment by vruusmann** [comment]
Did major OptBinning-to-PMML work in [SkLearn2PMML](https://github.com/jpmml/sklearn2pmml) version 0.89:

- Full support for `OptimalBinning` transformer class (numerical and categorical features; special and missing feature categories), and its `ContinuousOptimalBinning` and `MulticlassOptimalBinning` subclasses.
- Full support for the `BinningProcess` meta-transformer class.
- Almost-full support for the `Scorecard` estimator class. If the `Scorecard.scaling_method` attribute is set, then the converter generates a canonical [`Scorecard`](https://dmg.org/pmml/v4-4-1/Scorecard.html) PMML model element; otherwise, it generates "binning" PMML transformation elements, followed by a [`RegressionModel`](https://dmg.org/pmml/v4-4-1/Regression.html) PMML model element.

**Comment by guillermo-navas-palencia** [comment]
Hi @vruusmann,

That's great, thanks! SKLearn2PMML looks very interesting. Is there a tutorial about how to use it?

**Comment by vruusmann** [comment]
>  Is there a tutorial about how to use it (optbinning)?

I'm hoping to summarize my thoughts and findings in the form of a small blog post. Will insert a link to it right here when done.

In the meantime, one can take a look at the [optbinning.py](https://github.com/jpmml/jpmml-sklearn/blob/1.7.19/pmml-sklearn-extension/src/test/resources/extensions/optbinning.py) file (the same file as linked above; I'm anchoring my link to the SkLearn2PMML 0.89.1), which exemplifies how I generated my integration tests.

For example, here is how I prepared a regression-type Scorecard for the Auto-MPG dataset:
https://github.com/jpmml/jpmml-sklearn/blob/1.7.19/pmml-sklearn-extension/src/test/resources/extensions/optbinning.py#L148-L172
https://github.com/jpmml/jpmml-sklearn/blob/1.7.19/pmml-sklearn-extension/src/test/resources/extensions/optbinning.py#L179

Converting the resulting Pickle file [ScaledScorecardAuto.pkl](https://github.com/jpmml/jpmml-sklearn/blob/1.7.19/pmml-sklearn-extension/src/test/resources/pkl/ScaledScorecardAuto.pkl) to PMML:

```python
import joblib

pmml_pipeline = joblib.load("ScaledScorecardAuto.pkl")

from sklearn2pmml import sklearn2pmml

sklearn2pmml(pmml_pipeline, "ScaledScorecardAuto.pmml")
```
