### ISSUE TITLE
MulticlassOptimalBinning for categorical features

### ISSUE THREAD

**Issue by carefree0910** [guillermo-navas-palencia/optbinning#83]
Hi! It seems that `MulticlassOptimalBinning` does not support binning categorical features, is this intended? If it is, what method should I use instead? Thanks!

**Comment by guillermo-navas-palencia** [comment]
Hi, @carefree0910,

Yes, this decision was intentional. For binary and continuous target, categorical variables are encoded using target encoding. Thus, categories (sorted wrt to target mean) are replaced by the corresponding index and transformed into an ordinal variable. Finally, the binning algorithm is applied to the ordinal variable.

The sorting in terms of the multiclass target does not seem trivial to me. The ordering is important for merging prebins if constraints are not satisfied. If you could transform your categorical data to ordinal, then, the MulticlassOptimalBinning algorithm can be applied. 

I will investigate further, but any suggestions or PR would be very welcomed.

**Comment by carefree0910** [comment]
Thanks for your detailed explaination! @guillermo-navas-palencia 

Another issue I encountered is that it seems `OptimalBinning` is compatible with multi-class labels, however I'm not sure what the behaviour should be expected in this situation, or is this really valid after all? Thanks!

**Comment by guillermo-navas-palencia** [comment]
Hi,

It can accept multi-class labels if class 0 is included (the remaining will be treated as 1), but **it should not be used**. For performance purposes, I do not check if the target is truly binary, but this could be included.

I have tested that a pre-processing step using clustering techniques might be valid. It will let you know.

**Comment by carefree0910** [comment]
That sounds very reasonable, thanks again for the detailed explaination, and thanks for providing such a useful tool!
